/* Verilog netlist generated by SCUBA Diamond_1.1_Production (517) */
/* Module Version: 5.2 */
/* C:\lscc\diamond\1.1\ispfpga\bin\nt\scuba.exe -w -n pll -lang verilog -synth synplify -arch mg5a00 -type pll -fin 25 -phase_cntl DYNAMIC -trimp 0 -fclkop 75 -fclkop_tol 0.0 -fb_mode INTERNAL -duty50 -fdel 1 -noclkok -norst -noclkok2 -e  */
/* Thu Dec 23 15:34:31 2010 */


`timescale 1 ns / 1 ps
module pll (CLK, WRDEL, DPHASE0, DPHASE1, DPHASE2, DPHASE3, CLKOP, CLKOS, 
    LOCK)/* synthesis syn_noprune=1 */;// exemplar attribute pll dont_touch true 
    input wire CLK;
    input wire WRDEL;
    input wire DPHASE0;
    input wire DPHASE1;
    input wire DPHASE2;
    input wire DPHASE3;
    output wire CLKOP;
    output wire CLKOS;
    output wire LOCK;

    wire CLKOP_t;
    wire DPHASE3_inv;
    wire CLKFB_t;
    wire scuba_vlo;

    INV INV_0 (.A(DPHASE3), .Z(DPHASE3_inv));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    // synopsys translate_off
    defparam PLLInst_0.CLKOK_BYPASS = "DISABLED" ;
    defparam PLLInst_0.CLKOS_BYPASS = "DISABLED" ;
    defparam PLLInst_0.CLKOP_BYPASS = "DISABLED" ;
    defparam PLLInst_0.CLKOS_TRIM_DELAY = 0 ;
    defparam PLLInst_0.CLKOS_TRIM_POL = "RISING" ;
    defparam PLLInst_0.CLKOP_TRIM_DELAY = 0 ;
    defparam PLLInst_0.CLKOP_TRIM_POL = "FALLING" ;
    defparam PLLInst_0.PHASE_CNTL = "DYNAMIC" ;
    defparam PLLInst_0.DUTY = 8 ;
    defparam PLLInst_0.PHASEADJ = "0.0" ;
    defparam PLLInst_0.CLKOK_DIV = 2 ;
    defparam PLLInst_0.CLKOP_DIV = 8 ;
    defparam PLLInst_0.CLKFB_DIV = 3 ;
    defparam PLLInst_0.CLKI_DIV = 1 ;
    // synopsys translate_on
    EHXPLLE1 PLLInst_0 (.CLKI(CLK), .CLKFB(CLKFB_t), .RST(scuba_vlo), .RSTK(scuba_vlo), 
        .WRDEL(WRDEL), .DRPAI3(DPHASE3), .DRPAI2(DPHASE2), .DRPAI1(DPHASE1), 
        .DRPAI0(DPHASE0), .DFPAI3(DPHASE3_inv), .DFPAI2(DPHASE2), .DFPAI1(DPHASE1), 
        .DFPAI0(DPHASE0), .PWD(scuba_vlo), .CLKOP(CLKOP_t), .CLKOS(CLKOS), 
        .CLKOK(), .CLKOK2(), .LOCK(LOCK), .CLKINTFB(CLKFB_t))
             /* synthesis CLKOK_BYPASS="DISABLED" */
             /* synthesis CLKOS_BYPASS="DISABLED" */
             /* synthesis FREQUENCY_PIN_CLKOP="75.000000" */
             /* synthesis CLKOP_BYPASS="DISABLED" */
             /* synthesis CLKOS_TRIM_DELAY="0" */
             /* synthesis CLKOS_TRIM_POL="RISING" */
             /* synthesis CLKOP_TRIM_DELAY="0" */
             /* synthesis CLKOP_TRIM_POL="FALLING" */
             /* synthesis PHASE_CNTL="DYNAMIC" */
             /* synthesis DUTY="8" */
             /* synthesis PHASEADJ="0.0" */
             /* synthesis FREQUENCY_PIN_CLKOS="75.000000" */
             /* synthesis FREQUENCY_PIN_CLKI="25.000000" */
             /* synthesis FREQUENCY_PIN_CLKOK="50.000000" */
             /* synthesis CLKOK_DIV="2" */
             /* synthesis CLKOP_DIV="8" */
             /* synthesis CLKFB_DIV="3" */
             /* synthesis CLKI_DIV="1" */
             /* synthesis FIN="25.000000" */;

    assign CLKOP = CLKOP_t;


    // exemplar begin
    // exemplar attribute PLLInst_0 CLKOK_BYPASS DISABLED
    // exemplar attribute PLLInst_0 CLKOS_BYPASS DISABLED
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKOP 75.000000
    // exemplar attribute PLLInst_0 CLKOP_BYPASS DISABLED
    // exemplar attribute PLLInst_0 CLKOS_TRIM_DELAY 0
    // exemplar attribute PLLInst_0 CLKOS_TRIM_POL RISING
    // exemplar attribute PLLInst_0 CLKOP_TRIM_DELAY 0
    // exemplar attribute PLLInst_0 CLKOP_TRIM_POL FALLING
    // exemplar attribute PLLInst_0 PHASE_CNTL DYNAMIC
    // exemplar attribute PLLInst_0 DUTY 8
    // exemplar attribute PLLInst_0 PHASEADJ 0.0
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKOS 75.000000
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKI 25.000000
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKOK 50.000000
    // exemplar attribute PLLInst_0 CLKOK_DIV 2
    // exemplar attribute PLLInst_0 CLKOP_DIV 8
    // exemplar attribute PLLInst_0 CLKFB_DIV 3
    // exemplar attribute PLLInst_0 CLKI_DIV 1
    // exemplar attribute PLLInst_0 FIN 25.000000
    // exemplar end

endmodule
